[package]
name = "vercRust"
version = "0.1.0"
edition = "2021"
authors = ["encrypt0r <encrypt0r-x@protonmail.com>"]

[build]
target = "x86_64-unknown-linux-musl"

[[bin]]
name = "index"
path = "index.rs"

[dependencies]
tokio = "1.33.0"
vercel_runtime = "1.1.0"
